import js from '@eslint/js';

export default [
  {
    ignores: ['eslint.config.js', 'node_modules/**', 'styles/main.css', '*.min.js'],
  },
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        fetch: 'readonly',
        URLSearchParams: 'readonly',
        localStorage: 'readonly',
        $: 'readonly',
        jQuery: 'readonly',
        Swal: 'readonly',
        API_URL: 'readonly',
        apiRequest: 'readonly',
        authHeader: 'readonly',
        routeHref: 'readonly',
        getToken: 'readonly',
        Toast: 'writable',
        i18n: 'readonly',
        BkCurrency: 'readonly',
        BkDate: 'readonly',
        ThemeManager: 'readonly',
        Skeleton: 'readonly',
        initGoogleLogin: 'readonly',
        google: 'readonly',
        bootstrap: 'readonly',
        flowbite: 'readonly',
        BkSecurity: 'readonly',
        DOMParser: 'readonly',
        Node: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-undef': 'warn',
      'no-redeclare': 'warn',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'eqeqeq': ['warn', 'always', { null: 'ignore' }],
      'no-useless-escape': 'warn',
      'no-var': 'warn',
      'prefer-const': 'warn',
      'prefer-template': 'warn',
    },
  },
];
